version: '2'
services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ../../code:/var/www/html/
    links:
      - db-mysql
      - db-postgress
      - db-mariadb
    container_name: dev_web_php56

  db-mysql:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - ./config/mysql-server:/etc/mysql
      - ./logs/mysql_logs:/var/log
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: dev_mysql_php56

  db-postgress:
      image: postgres
      environment:
          POSTGRES_PASSWORD: postgres
      restart: always
      container_name: dev_pg_php56

  db-mariadb:
    image: mariadb
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: dev_mariadb_php56

