version: '2'
services:
  web:
    image: php:7-apache
    ports:
      - "8082:80"
    volumes:
      - ../../code:/var/www/html/
    links:
      - db
    container_name: dev_web_php7

  db:
    image: mysql:5.5
    expose:
      - "3306"
    volumes:
      - ./config/mysql-server:/etc/mysql
      - ./logs/mysql_logs:/var/log
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: dev_mysql_php7
